plugins {
    id 'java'
    id 'application'
}

group = 'at.fhv'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.jfree:jfreechart:1.5.4'
    implementation 'com.google.code.gson:gson:2.11.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'at.fhv.Main'
    applicationDefaultJvmArgs = ['-Xmx4g']
}

run {
    workingDir = project.projectDir
}